version: '3.4'
networks:
  grupo8:
    driver: bridge

services:  
  reservations-backend:
    container_name: reservations-backend
    build: .
    ports:
      - 8088:8088
    volumes:
      - ./:/usr/src/app
    networks:
      - grupo8
    depends_on:
      - database

  database:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./.dataMongo:/data/db
    networks:
      - grupo8